
export const ADD_FOOD = 'ADD_FOOD'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const UPDATE_CHECKOUT = 'UPDATE_CHECKOUT'
export const CANCEL_CHECKOUT = 'CANCEL_CHECKOUT'
export const GET_CHECKOUT = 'GET_CHECKOUT'

export const ADD_TO_FRIEND = 'ADD_TO_FRIEND'
export const GET_FRIEND = 'GET_FRIEND'
export const REMOVE_FRIEND_ITEM = 'REMOVE_FRIEND_ITEM'
export const CANCEL_FRIEND = 'CANCEL_FRIEND'

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const SET_BLUR = 'SET_BLUR'